export const cuisineList = [
    "African",
    "American",
    "Asian",
    "Bakery",
    "Barbecue",
    "Brazilian",
    "Breakfast",
    "British",
    "Burgers",
    "Cafe",
    "Caribbean",
    "Chinese",
    "Desserts",
    "European",
    "Fast Food",
    "French",
    "German",
    "Greek",
    "Grill",
    "Healthy",
    "Ice Cream",
    "Indian",
    "Italian",
    "Japanese",
    "Kebab",
    "Korean",
    "Lebanese",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Peruvian",
    "Pasta",
    "Pizza",
    "Salad",
    "Sandwich",
    "Seafood",
    "Spanish",
    "Sushi",
    "Thai",
    "Turkish",
    "Vegetarian",
    "Vietnamese",
];